name: Build Angular in Github Action Workflow
on:
  push:
    branches:
      - master

jobs:

  Build_Angular_App:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-node@v1
      with:
        node-version: 12.16.2
      name: Install Node.js

    - run: |
        npm install
        npm install -g @angular/cli
        npm run lint
        npm run build --prod
      name: npm install and build

    - uses: actions/upload-artifact@v1
      with:
        name: WorkflowvsPipeline
        path: WorkflowvsPipeline/dist/WorkflowvsPipeline
      name: Publish Artifact